parameters:
  - name: runningAgent
    displayName: Pick agent to run
    type: string
    default: ubuntu-latest
    values:
      - ubuntu-latest
      - azp-agent-ubuntu-docker
      - azp-agent-debian-docker
      - azp-agent-debian-docker-local

  - name: dependencies
    type: stepList
    default:
      - checkout: self

  - name: terraformVersion
    displayName: Terraform version
    type: string
    default: 1.8.5

  - name: tfWorkDir
    displayName: Terraform working directory
    type: string
    default: .

  - name: tfVarsFile
    displayName: Optional tfvars file path
    type: string
    default: ""

  - name: sshSecretName
    type: string
    default: ""

  - name: sshKeyName
    type: string
    default: ""

  - name: awsAccessKeyId
    displayName: AWS Access Key ID for terraform backend
    type: string
    default: ""

  - name: awsSecretAccessKey
    displayName: AWS Secret Access Key for terraform backend
    type: string
    default: ""

  - name: awsRegion
    displayName: AWS Region for terraform backend
    type: string
    default: ""

stages:
  - stage: Prepare
    displayName: Prepare Secrets
    jobs:
      - job: GenerateSSHKey
        displayName: Generate SSH Key

        steps:
          - bash: |
              mkdir -p .ssh-temp
              PRIVATE_KEY_FILE=".ssh-temp/id_ed25519"
              PUBLIC_KEY_FILE=".ssh-temp/id_ed25519.pub"

              echo "Generating SSH key pair..."

              ssh-keygen \
                -t ed25519 \
                -N "" \
                -f "${PRIVATE_KEY_FILE}" \
                -C "${SSH_KEY_NAME}"

              # echo "Uploading private key to AWS Secrets Manager..."
              # aws sts get-caller-identity
              # set -euo pipefail
              # aws secretsmanager create-secret \
              #   --name "${SSH_KEY_NAME}-private-key" \
              #   --secret-string "file://${PRIVATE_KEY_FILE}" \
              #   || aws secretsmanager put-secret-value \
              #     --secret-id "${SSH_KEY_NAME}-private-key" \
              #     --secret-string "file://${PRIVATE_KEY_FILE}"

              # echo "Uploading public key to AWS Secrets Manager..."

              # aws secretsmanager create-secret \
              #   --name "${SSH_KEY_NAME}-public-key" \
              #   --secret-string "file://${PUBLIC_KEY_FILE}" \
              #   || aws secretsmanager put-secret-value \
              #     --secret-id "${SSH_KEY_NAME}-public-key" \
              #     --secret-string "file://${PUBLIC_KEY_FILE}"

              # echo "Cleaning up local key files..."

              # rm -rf .ssh-temp

              # echo "SSH keys uploaded successfully."
            env:
              SSH_KEY_NAME: ${{ parameters.sshKeyName }}
            displayName: Generate and upload SSH keys

          - bash: |
              aws sts get-caller-identity
            env:
              AWS_ACCESS_KEY_ID: ${{ parameters.awsAccessKeyId }}
              AWS_SECRET_ACCESS_KEY: ${{ parameters.awsSecretAccessKey }}
              AWS_REGION: ${{ parameters.awsRegion }}
              SSH_KEY_NAME: ${{ parameters.sshKeyName }}
            displayName: Verify AWS Credentials

          - bash: |
              PRIVATE_KEY_FILE=".ssh-temp/id_ed25519"
              PUBLIC_KEY_FILE=".ssh-temp/id_ed25519.pub"

              echo "Uploading private key to AWS Secrets Manager..."
              aws secretsmanager create-secret \
                --name "${SSH_KEY_NAME}-private-key" \
                --secret-string "file://${PRIVATE_KEY_FILE}" \
                || aws secretsmanager put-secret-value \
                  --secret-id "${SSH_KEY_NAME}-private-key" \
                  --secret-string "file://${PRIVATE_KEY_FILE}"

              echo "Uploading public key to AWS Secrets Manager..."

              aws secretsmanager create-secret \
                --name "${SSH_KEY_NAME}-public-key" \
                --secret-string "file://${PUBLIC_KEY_FILE}" \
                || aws secretsmanager put-secret-value \
                  --secret-id "${SSH_KEY_NAME}-public-key" \
                  --secret-string "file://${PUBLIC_KEY_FILE}"

              echo "Cleaning up local key files..."
              rm -rf .ssh-temp
              echo "SSH keys uploaded successfully."
            env:
              AWS_ACCESS_KEY_ID: ${{ parameters.awsAccessKeyId }}
              AWS_SECRET_ACCESS_KEY: ${{ parameters.awsSecretAccessKey }}
              AWS_REGION: ${{ parameters.awsRegion }}
              SSH_KEY_NAME: ${{ parameters.sshKeyName }}
            displayName: Upload SSH keys to AWS Secrets Manager

          - bash: |
              echo "##vso[build.addbuildtag]${SSH_KEY_NAME}"
            env:
              SSH_KEY_NAME: ${{ parameters.sshKeyName }}
            displayName: Add pipeline tags
