parameters:
  - name: runningAgent
    displayName: Pick agent to run
    type: string
    default: azp-agent-ubuntu-docker
    values:
      - ubuntu-latest
      - azp-agent-ubuntu-docker
      - azp-agent-debian-docker

  - name: dependencies
    type: stepList
    default:
      - checkout: self
      - checkout: one-press-functions

  - name: condaBinPath
    type: string
    default: "/opt/miniconda3/bin"

  - name: workspaceWorkDir
    type: string
    default: "$(Agent.BuildDirectory)/w"

  - name: requiredInfrastructureVars
    displayName: Uri of docker
    type: object
    default: ""

  - name: requiredProjectVars
    displayName: Uri of docker
    type: object
    default: ""

  - name: functionsWorkDir
    type: string
    default: "$(System.DefaultWorkingDirectory)/one-press-functions"

  - name: functionsResources
    type: string
    default: "app/functions"

  - name: functions
    type: object
    default:
      initializeStages: initialize_stages_ado_func.py
      helmUpgrade: helm_upgrade_func.py

  - name: pythonVenvPath
    type: string
    displayName: Virtual environment path for python
    default: "/data/.conda/envs"

  - name: functionsVenv
    type: string
    displayName: Name of functions venv
    default: "one-press-functions"

  - name: targetProjectPath
    type: string
    default: $(System.DefaultWorkingDirectory)/$(Build.Repository.Name)

  - name: appResource
    type: string
    default: resources/app

  - name: k8sResource
    type: string
    default: resources/k8s

  - name: environments
    type: object
    default:
      - DEV
      - UAT

  - name: targetProject
    type: string
    default: $(System.TeamProject)

  - name: targetProjectPipeline
    type: string
    default: ""

  - name: targetProjectResource
    type: string

  - name: buildVersionToDownload
    type: string
    default: "latest"

  - name: artifactName
    type: string
    default: "bootstrap"

  - name: helmChartName
    type: string
    default: "one-press-chart"

  - name: helmChartVersion
    type: string
    default: "0.1.0"

  - name: publishFileName
    displayName: Name of artifact.
    type: string
    default: "metadata.json"

  - name: requiredProjectConfigurationVars
    displayName: Name of artifact.
    type: object
    default: ""

stages:
  - ${{ each env in parameters.environments }}:
      - stage: ${{ env }}
        jobs:
          - deployment: Deploy_${{ env }}
            displayName: Deploy ${{ env }}
            workspace:
              clean: all
            pool:
              ${{ if eq(parameters.runningAgent, 'ubuntu-latest') }}:
                vmImage: ${{ parameters.runningAgent }}
              ${{ if eq(parameters.runningAgent, 'azp-agent-ubuntu-docker') }}:
                name: ${{ parameters.runningAgent }}
              ${{ if eq(parameters.runningAgent, 'azp-agent-debian-docker') }}:
                name: ${{ parameters.runningAgent }}
            variables:
              - template: vars-cicd-k8s-${{ lower(env) }}.yml
              - template: vars-cicd-k8s.yml
            environment:
              name: "K8S_${{ env }}"
            strategy:
              runOnce:
                deploy:
                  steps:
                    - download: none

                    - ${{ parameters.dependencies }}

                    - task: AzureKeyVault@2
                      inputs:
                        azureSubscription: ${{ variables.FLOW_INFRA_CONFIG_VAULT_SERVICE_CONNECTION }}
                        KeyVaultName: ${{ variables.FLOW_INFRA_CONFIG_VAULT_NAME }}
                        SecretsFilter: ${{ join(',',parameters.requiredInfrastructureVars) }}
                        RunAsPreJob: true
                      displayName: "Bootstrap: Fetch vars from vault"

                    - task: AzureKeyVault@2
                      inputs:
                        azureSubscription: ${{ variables.FLOW_PROJECT_CONFIG_VAULT_SERVICE_CONNECTION }}
                        KeyVaultName: ${{ variables.FLOW_PROJECT_CONFIG_VAULT_NAME }}
                        SecretsFilter: ${{ join(',',parameters.requiredProjectVars) }}
                        RunAsPreJob: true
                      displayName: "Bootstrap: Fetch vars from vault"
                      condition: ${{ ne(parameters.requiredProjectVars, '') }}

                    - bash: |
                        echo "##vso[task.setvariable variable=PATH;]${CONDA_BIN_PATH}:${PATH}"
                        echo "##vso[task.setvariable variable=PYTHONPATH;]${FUNCTIONS_WORK_DIR}:${PYTHONPATH}"
                      env:
                        CONDA_BIN_PATH: ${{ parameters.condaBinPath }}
                        FUNCTIONS_WORK_DIR: "${{ parameters.functionsWorkDir }}"
                      displayName: "Bootstrap: Initialize functions env"

                    - bash: |
                        source activate $FUNCTIONS_VENV
                        python ${{ parameters.functionsWorkDir }}/app/main.py INITIALIZE_WORKSPACE
                      env:
                        FUNCTIONS_VENV: ${{ parameters.functionsVenv }}
                        SUIT_UP_SCRIPT_PATH: "${{ parameters.functionsWorkDir }}/${{ parameters.functionsResources }}/${{ parameters.functions.initializeStages }}"
                        STAGE_NAME: DEPLOYMENT
                        DEPLOYMENT_PREFIX_PATH: ${{ parameters.workspaceWorkDir }}
                      displayName: "Bootstrap: Set up stage"

                    - task: DownloadPipelineArtifact@2
                      inputs:
                        buildType: "specific"
                        project: "${{ parameters.targetProject }}"
                        definition: "${{ parameters.targetProjectPipeline }}"
                        buildVersionToDownload: "${{ parameters.buildVersionToDownload }}"
                        artifactName: "${{ parameters.artifactName }}"
                        pipelineId: "${{ parameters.buildVersionToDownload }}"
                        targetPath: $(FLOW_DEPLOYMENT_SECTION_DIR)
                      displayName: "Deployment: Download pipeline artifact"

                    - bash: |
                        # echo "${GKE_SA_KEY}" | base64 --decode > gke-sa-key.json
                        # gcloud auth activate-service-account --key-file=gke-sa-key.json
                        # gcloud components install kubectl
                        # gcloud components install gke-gcloud-auth-plugin
                        # export USE_GKE_GCLOUD_AUTH_PLUGIN=True
                        source activate $FUNCTIONS_VENV
                        python ${{ parameters.functionsWorkDir }}/app/main.py HELM_UPGRADE
                      env:
                        FUNCTIONS_VENV: ${{ parameters.functionsVenv }}
                        HELM_UPGRADE_SCRIPT_PATH: "${{ parameters.functionsWorkDir }}/${{ parameters.functionsResources }}/${{ parameters.functions.helmUpgrade }}"
                        DEPLOYMENT_WORK_DIR: $(FLOW_DEPLOYMENT_SECTION_DIR)
                        PUBLISH_FILE_PATH: $(FLOW_DEPLOYMENT_SECTION_DIR)/${{ parameters.publishFileName }}
                        ENVIRONMENT: ${{ env }}
                        PROJECT_PATH: ${{ parameters.targetProjectPath }}/pipelines/${{ parameters.targetProjectResource }}
                        PROJECT_NAME: ${{ parameters.targetProjectResource }}
                        APP_RESOURCES: ${{ parameters.appResource }}
                        K8S_RESOURCES: ${{ parameters.k8sResource }}
                        HELM_CHART_NAME: ${{ parameters.helmChartName }}
                        HELM_CHART_VERSION: ${{ parameters.helmChartVersion  }}
                        HELM_SERVER_URI: $(SECRET-DOCKER-SERVER-URI)
                        HELM_SERVER_USERNAME: $(SECRET-DOCKER-SERVER-USERNAME)
                        HELM_SERVER_PASSWORD: $(SECRET-DOCKER-SERVER-PASSWORD)
                        GKE_SA_KEY: $(GKE-SA-KEY)
                        USE_GKE_GCLOUD_AUTH_PLUGIN: True
                        KUBE_CONFIG_CONTENT: $(SECRET-K8S-KUBECONFIG-CONTENT-${{ env }})
                        IS_SCAN_AZURE_SECRETS_VAULT: true
                        ${{ if ne(parameters.requiredProjectVars, '') }}:
                          ${{ each env_p  in parameters.requiredProjectVars }}:
                            ${{ env_p }}: "$(${{ env_p }})"
                      displayName: "Deployment: Helm deploy"
