parameters:
  - name: runningAgent
    displayName: Pick agent to run
    type: string
    default: ubuntu-latest
    values:
      - ubuntu-latest
      - azp-agent-ubuntu-docker
      - azp-agent-debian-docker
      - azp-agent-debian-docker-local

  - name: dependencies
    type: stepList
    default:
      - checkout: self

  - name: terraformVersion
    displayName: Terraform version
    type: string
    default: 1.8.5

  - name: tfWorkDir
    displayName: Terraform working directory
    type: string
    default: .

  - name: tfVarsFile
    displayName: Optional tfvars file path
    type: string
    default: ""

  - name: sshKeygenComment
    type: string
    default: ""

  - name: sshDir
    type: string
    default: ".ssh-temp"

  - name: privateKeyName
    type: string
    default: "ed25519"

  - name: publicKeyName
    type: string
    default: "ed25519.pub"

  - name: awsAccessKeyId
    displayName: AWS Access Key ID for terraform backend
    type: string
    default: ""

  - name: awsSecretAccessKey
    displayName: AWS Secret Access Key for terraform backend
    type: string
    default: ""

  - name: awsRegion
    displayName: AWS Region for terraform backend
    type: string
    default: ""

stages:
  - stage: Prepare
    displayName: Prepare Secrets
    jobs:
      - job: GenerateSSHKey
        displayName: Generate SSH Key

        steps:
          - bash: |
              mkdir -p "${SSH_DIR}"
              PRIVATE_KEY_FILE="${SSH_DIR}/${PRIVATE_KEY_NAME}"
              PUBLIC_KEY_FILE="${SSH_DIR}/${PUBLIC_KEY_NAME}"

              echo "Generating SSH key pair..."

              ssh-keygen \
                -t ed25519 \
                -N "" \
                -f "${PRIVATE_KEY_FILE}" \
                -C "${SSH_KEYGEN_COMMENT}"
            env:
              SSH_KEYGEN_COMMENT: ${{ parameters.sshKeygenComment }}
              SSH_DIR: ${{ parameters.sshDir }}
              PRIVATE_KEY_NAME: ${{ parameters.privateKeyName }}
              PUBLIC_KEY_NAME: ${{ parameters.publicKeyName }}
            displayName: Generate SSH keys

          - bash: |
              aws sts get-caller-identity
            env:
              AWS_ACCESS_KEY_ID: ${{ parameters.awsAccessKeyId }}
              AWS_SECRET_ACCESS_KEY: ${{ parameters.awsSecretAccessKey }}
              AWS_REGION: ${{ parameters.awsRegion }}
            displayName: Verify AWS Credentials

          - bash: |
              set -euo pipefail

              PRIVATE_KEY_FILE="${SSH_DIR}/${PRIVATE_KEY_NAME}"
              PUBLIC_KEY_FILE="${SSH_DIR}/${PUBLIC_KEY_NAME}"

              echo "Uploading private key to AWS Secrets Manager..."
              aws secretsmanager create-secret \
                --name ${AWS_SM_PRIVATE_KEY_NAME} \
                --secret-string "file://${PRIVATE_KEY_FILE}" \
                || aws secretsmanager put-secret-value \
                  --secret-id ${AWS_SM_PRIVATE_KEY_NAME} \
                  --secret-string "file://${PRIVATE_KEY_FILE}"

              echo "Uploading public key to AWS Secrets Manager..."

              aws secretsmanager create-secret \
                --name "${AWS_SM_PUBLIC_KEY_NAME}" \
                --secret-string "file://${PUBLIC_KEY_FILE}" \
                || aws secretsmanager put-secret-value \
                  --secret-id "${AWS_SM_PUBLIC_KEY_NAME}" \
                  --secret-string "file://${PUBLIC_KEY_FILE}"

              echo "Cleaning up local key files..."
              rm -rf "${SSH_DIR}"
              echo "SSH keys uploaded successfully."
            env:
              SSH_DIR: ${{ parameters.sshDir }}
              PRIVATE_KEY_NAME: ${{ parameters.privateKeyName }}
              PUBLIC_KEY_NAME: ${{ parameters.publicKeyName }}
              AWS_ACCESS_KEY_ID: ${{ parameters.awsAccessKeyId }}
              AWS_SECRET_ACCESS_KEY: ${{ parameters.awsSecretAccessKey }}
              AWS_REGION: ${{ parameters.awsRegion }}
              AWS_SM_PRIVATE_KEY_NAME: ${{ parameters.sshKeygenComment }}-private-key
              AWS_SM_PUBLIC_KEY_NAME: ${{ parameters.sshKeygenComment }}-public-key
            displayName: Upload SSH keys to AWS Secrets Manager

          - bash: |
              echo "##vso[build.addbuildtag]${AWS_SM_PRIVATE_KEY_NAME}"
              echo "##vso[build.addbuildtag]${AWS_SM_PUBLIC_KEY_NAME}"
            env:
              AWS_SM_PRIVATE_KEY_NAME: ${{ parameters.sshKeygenComment }}-private-key
              AWS_SM_PUBLIC_KEY_NAME: ${{ parameters.sshKeygenComment }}-public-key
            displayName: Add pipeline tags
